name: Build and Deploy Application and Infrastructure

on:
  push:
    branches:
    - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13.3'
    - run: |
        go get -d -v
        GOOS=linux go build -o crud-app
        mkdir dist
        tar czvf dist/crud-app.tar.gz crud-app form/*
      working-directory: src
    - uses: actions/upload-artifact@master
      with:
        name: crud-app
        path: src/dist
