name: Build and Deploy Application and Infrastructure

on:
  push:
    branches:
    - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13.3'
    - run: |
        go get -d -v
        GOOS=linux go build -o crud-app
        mkdir dist
        tar czvf dist/crud-app.tar.gz crud-app form/*
      working-directory: src
      name: Build artifact
#    - uses: actions/upload-artifact@master
#      name: Store artifact
#      with:
#        name: crud-app
#        path: src/dist
    - name: Upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: aws s3 cp src/dist/crud-app.tar.gz s3://3r1co-github-artifacts --region us-east-1
    - name: Upload CloudFormation
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: aws cloudformation deploy --template-file files/cf-all.yaml --stack-name isen --parameter-overrides
            UpdateVariable="$(date)"
            DBName="${{ secrets.DBName }}"
            DBPassword="${{ secrets.DBPassword }}"
            DBRootPassword="${{ secrets.DBRootPassword }}"
            DBUser="${{ secrets.DBUser }}"
            KeyName="${{ secrets.KeyName }}"
            InstanceTypeParameter="t2.micro"
            --region us-east-1